services:
  frontend:
    hostname: frontend
    environment:
      - PORT=8080
      - VITE_BACKEND_URL=http://backend:8000
    build:
      context: ./web-peladaapp
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./web-peladaapp/src:/app/src
      - ./web-peladaapp/public:/app/public
      - ./web-peladaapp/index.html:/app/index.html
      - ./web-peladaapp/vite.config.ts:/app/vite.config.ts
      - ./web-peladaapp/tsconfig.json:/app/tsconfig.json
      - ./web-peladaapp/tsconfig.app.json:/app/tsconfig.app.json
    depends_on:
      - backend

  backend:
    hostname: backend
    environment:
      - PELADA_API_SECURITY_SIGNING_KEY=secret-for-dev-only-not-for-prod
      - WAHA_API_KEY=${WAHA_API_KEY:-dev-api-key}
    build:
      context: ./api-peladaapp
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api-peladaapp:/app

  waha:
    image: ${WAHA_IMAGE:-devlikeapro/waha:arm}
    restart: always
    environment:
      - WAHA_API_KEY=${WAHA_API_KEY:-dev-api-key}
      - WAHA_DASHBOARD_PASSWORD=ee54354c72854f2283a373c064c7eeb8
      - WHATSAPP_SWAGGER_PASSWORD=ee54354c72854f2283a373c064c7eeb8
      - WHATSAPP_API_BASE_URL=/waha/
      - WAHA_DASHBOARD_ENABLED=true
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
