apiVersion: v1
kind: Secret
metadata:
  name: keel-secrets
  namespace: keel
type: Opaque
stringData:
  KEEL_PORTAL_USER: "admin" # THIS IS YOUR DEFAULT USER. Change it manually on the server.
  KEEL_PORTAL_PASSWORD: "admin" # THIS IS YOUR DEFAULT PASSWORD. Change it manually on the server.
